index.js
package-lock.json
package.json
src/fastly/dictionaries.js
src/publish.js
test/dictionaries.test.js
test/integration.js

Depends on adobe/fastly-native-promises#27

WIP: Provide an integration test

---

package-lock.json
package.json

Greenkeeper/@adobe/fastly native promises 1.6.0

---

layouts/fastly/helix.vcl
src/fastly/vcl-utils.js
test/fixtures/full-resolve.vcl
test/fixtures/noconditions-resolve.vcl
test/fixtures/urls-resolve.vcl

This is an attempt to merge #12 and #7 in order to fix #11

Fix Dirnames

---

layouts/fastly/helix.vcl

Only append params if there are params

---

.gitignore
CONTRIBUTING.md
package-lock.json
package.json
test/troubleshoot.js

Fixes #36 
Introduces a testing tool for troubleshooting these kinds of issues.

Fix for duplicate dictionary creation

---

layouts/fastly/helix.vcl

Helps with #39 (other issues remain)
- adds more tracing to `hlx_strain`
- makes fixes the condition to treat `""` as no strain
@acme

Fix Strain Resolution

---

layouts/fastly/helix.vcl
src/fastly/vcl-utils.js
test/fixtures/full-resolve.vcl
test/fixtures/urls-resolve.vcl

- update test fixtures
- add tracing to hlx_request_type
fixes #39 depends on #40

change X-Static to X-Request-Type for Proxy Strains

---

layouts/fastly/helix.vcl

Fixes #42 
- use slashes in the right places
- don't use static repo, etc. for dynamic content

Fix pipeline, fixes #42

---

src/fastly/dictionaries.js
test/dictionaries.test.js
test/fixtures/full.yaml

fix(dictionaries): set missing directory index

---

package-lock.json
package.json

Greenkeeper/@adobe/helix shared 1.0.1

---

index.js
layouts/fastly/extensions.vcl
layouts/fastly/helix.vcl
src/fastly/vcl.js
src/publish.js
test/integration.js
test/vcl.test.js

PR for https://github.com/adobe/helix-publish/issues/85

feat(vcl): Add extensions.vcl

---

.vscode/launch.json
README.md
index.js
layouts/fastly/extensions.vcl
src/fastly/include-util.js
src/fastly/vcl.js
src/publish.js
test/include-util.test.js
test/vcl.test.js

feat(vcl): Support Custom VCL

---

layouts/fastly/extensions.vcl
layouts/fastly/helix.vcl

PR for #92 
Arff... depends on https://github.com/adobe/helix-publish/pull/87

feat(vcl): Provide hlx_owner, hlx_repo and hlx_ref extension points

---

layouts/fastly/helix.vcl

fix X-Trace #97

---

layouts/fastly/helix.vcl

fix(vcl): respect remapped url also in static

---

index.js
package-lock.json
package.json

See the last step in https://circleci.com/gh/adobe/helix-publish/630 for an example of the status response:
```xml
<pingdom_http_custom_check>
<status>OK</status>
<version>1.3.0</version>
<response_time>61</response_time>
<fastly>27</fastly>
</pingdom_http_custom_check>
```

refactor(index): use helix-pingdom-status for status reporting

---

layouts/fastly/helix.vcl

feat(dispatch): use latest instead of v1

---

package-lock.json
package.json

Greenkeeper/@adobe/helix shared 2.0.0

---

layouts/fastly/helix.vcl

fix(dispatch): add params.rootPath

---

package-lock.json
package.json
test/fixtures/recordings/Integration-Test_519117731/Test-publish-function-locally_1268185746/recording.har
test/integration.js

tests(integration): use pollyjs to enble offline testing

---

layouts/fastly/helix.vcl

fix(vcl): don't send synthetic errors for esi sub-requests

---

index.js

fix(monitoring): hide Epsagon and Fastly token from Epsagon

---

.circleci/config.yml
index.js
package-lock.json
package.json

… and enable automated New Relic Monitoring

Use the new Status Library

---

layouts/fastly/helix.vcl

fix(vlc): ensure that static redirect is handled before errors

---

layouts/fastly/helix.vcl

feat(vcl): pass github token via header on backend request

---

package-lock.json
package.json

Greenkeeper/@adobe/helix status 4.3.6

---

layouts/fastly/helix.vcl

Fixes order of trace stmts in X-Trace header

fix(helix.vcl) - trace header stmt sequence

---

layouts/fastly/helix.vcl
src/fastly/backends.js
test/backends.test.js
test/fixtures/demo-reset.vcl
test/fixtures/full-reset.vcl
test/fixtures/recordings/Integration-Test_519117731/Test-publish-function-locally_1268185746/recording.har

Adds a new request type for URLs like `098af326aa856bb42ce9a21240cf73d6f64b0b45.jpg`, which will get relayed to `098af326aa856bb42ce9a21240cf73d6f64b0b45` and cached indefinitely, as the content is immutable.

Blobxy: Support for Azure Blob Proxy

---

CHANGELOG.md
layouts/fastly/helix.vcl
package-lock.json
package.json

feat(vcl): adds cgi-bin request type

---

layouts/fastly/helix.vcl

feat(sitemap): allow ESI in XML, pass (owner,repo,ref) to cgi-bin

---

layouts/fastly/helix.vcl

feat(vcl): add X-CDN-URL with full URL

---

layouts/fastly/helix.vcl

fix(vcl): X-CDN-Request-ID pattern typo

---

layouts/fastly/helix.vcl

feat(helix.vcl): preserve ow activation id for logging

---

package-lock.json
package.json
src/fastly/vcl-utils.js
test/fixtures/recordings/Integration-Test_519117731/Test-publish-function-locally_1268185746/recording.har
test/redirects.test.js
test/vcl-utils.test.js

Robust rewrites

---

src/fastly/backends.js

fix(backends): disable SSL host verification for fonts backend

---

src/fastly/vcl-utils.js
test/fixtures/urls_legacy-resolve.vcl
test/fixtures/urls_legacy.yaml
test/vcl-utils.test.js

fix(strains): implicit url condition is not backward compatible

---

layouts/fastly/helix.vcl

fix(vcl): make sure activation id gets logged when serving error pages

---

layouts/fastly/helix.vcl

fix(vcl): make sure trace is complete and returned in synthetic errors

---

layouts/fastly/helix.vcl

feat(blob): support SVG

---

layouts/fastly/helix.vcl

fix(vcl): serve 429 error page when no response body exists

---

layouts/fastly/helix.vcl

feat(vcl): add hlx-forwarded-host header

---

layouts/fastly/helix.vcl

the only request type where it was enabled was hlx-blob
fixes #318

Re-enable image optimization for all relevant request types

---

layouts/fastly/helix.vcl

fixes #451 (this time for real)

fix(vcl): forward x-forwarded-host as hlx-forwarded-host to fix runtime

---

src/vcl/schemahelper.js
test/schemahelper.test.js

fix(epsagon): escape strings in json

---

src/vcl/tracer.js

fix(epsagon): add method (again)

---

layouts/fastly/helix.vcl

see https://github.com/adobe/helix-content-proxy/issues/55

feat(content-proxy): pass along querybuilder parameters

---

layouts/fastly/helix.vcl

fix(vcl): relax the block list a bit for ESI

---

layouts/fastly/helix.vcl

fix(vcl): keep last-activation-id around for epsagon

---

layouts/fastly/helix.vcl

fix(helix.vcl): remove chatty image headers

---

layouts/fastly/helix.vcl

fixes https://github.com/adobe/project-helix/issues/461

fix(frames): deny usage in frames

---

layouts/fastly/helix.vcl

fixes https://github.com/adobe/project-helix/issues/460

fix(vcl): Vary on XFH

---

layouts/fastly/helix.vcl

fix(vcl): suppress Age header

---

layouts/fastly/helix.vcl

fix(vcl): allow frames on same domain

---

src/publish.js

BREAKING CHANGE: uses the new dispatch version that removes dynamic defaults and the README.html directory index
fixes #519

fix(dispatch): use new dispatch version

---

package-lock.json
package.json
test/integration.js

test(integration): replace request with chai-http

---

src/fastly/vcl.js
src/publish.js
test/integration.js
test/vcl.test.js

fix: make sure "helix.vcl" ends up being the "main" script

---

layouts/fastly/helix.vcl

fixes #556
@trieloff  Not sure if/how this should work.
- I don't understand how the `secrets` dictionary is updated
- does the `+` work, if the item is not in the dictionary? would it just return an empty string?

feat(blobs): include SAS token for fetching blobs if configured

---

layouts/fastly/helix.vcl

feat(static): allow redirect requests from the outside

---

layouts/fastly/helix.vcl

refactor(vcl): better vary syntax

---

layouts/fastly/helix.vcl

feat(vcl): add surrogate keys for repo and url

---

layouts/fastly/helix.vcl

by forwarding to helix-purge
see https://github.com/adobe/helix-home/issues/145

feat(vcl): enable deep purges

---

src/check-pkgs.js
test/check-pkg.test.js
test/integration.js

fix(check): use html/_status_check instead of hlx--static

---

test/integration.js

@MarquiseRosier is this the test that you ran?

test(integration): add guardrails

---

layouts/fastly/helix.vcl

fix(purge): ignore url params for hlxpurge

---

layouts/fastly/helix.vcl

it should be possible to address all blobs in azure.

feat(blobs): allow all extenions for azure blobs

---

.circleci/config.yml

Fix #625 
NOTE: first merge https://github.com/adobe/helix-pages/pull/489, then remove hardcoded branch in config and then merge this one.

chore(ci): run helix-pages smoke tests

---

layouts/fastly/helix.vcl

feat(vcl): add Vary header on version lock

---

.circleci/config.yml
test/post-deploy.test.js

Depends on https://github.com/adobe/helix-pages/pull/519

Post publish tests

---

layouts/fastly/helix.vcl

feat(helix.vcl): only optimize image requests with query params

---

layouts/fastly/helix.vcl

fix(purge): support azure

---

layouts/fastly/helix.vcl

feat(preflight): include repo/owner/ref

---

layouts/fastly/helix.vcl

fix(vcl): prevent 503 max restarts error

---

src/rgx/block.js
test/fixtures/blocked-paths.txt

Block more

---

src/check-pkgs.js
test/check-pkg.test.js
test/fixtures/pass.yaml

Validate universal runtime

---

src/check-pkgs.js

fix(checks): do not check universal runtime packages

---

layouts/fastly/helix.vcl

Fix for #718, but the way @davidnuescheler likes it.

Media urls

---

layouts/fastly/helix.vcl

fixes #725
alternative to #726

fix(preflight): make sure preflight requests are always made with owner, repo, ref

---

layouts/fastly/helix.vcl

Fix universal runtime double slashes

---

layouts/fastly/helix.vcl

fix(vcl): fix nullable root path for universal runtime

---

layouts/fastly/helix.vcl

fix(vcl): use X-OW-Version-Lock consistently

---

layouts/fastly/helix.vcl

fix(universal): fix restart issue with universal runtime

---

package-lock.json
package.json
src/check-pkgs.js

fix(deps): migrate to helix-fetch v2

---

layouts/fastly/helix.vcl
package-lock.json
package.json
src/publish.js

build(deps): bump fastly-native-promises

---

layouts/fastly/helix.vcl

feat: cleanup headers sent to backend

---

layouts/fastly/helix.vcl

Allows to pass the usual lookup, when caching is **not** desired at all

fix(vcl): allow returning pass from vcl_recv

---

layouts/fastly/400.html
layouts/fastly/helix.vcl
package.json

- feat(sitemap): serve sitemap.xml from content proxy
- feat(vcl): allow sitemaps anywhere
- fix(vcl): propagate error 400 from any backend to the client

handle error 400

---

layouts/fastly/405.html
layouts/fastly/helix.vcl
package.json

fix(vcl): handle unknown methods

---

layouts/fastly/helix.vcl

see https://github.com/adobe/helix-content-proxy/issues/328

feat(vcl): use content-proxy for .lnk extension

---

layouts/fastly/helix.vcl

for the new blob hashes we need to allow longer sequences.

fix(vcl): allow wider blob hash

---

package-lock.json
package.json
src/check-pkgs.js
src/index.js
src/publish.js

fix(check): better error reporting when json parsing fails

---

layouts/fastly/helix.vcl

up to this change, the github token would always be taken from a globally shared token, making it impossible to have truly private repositories for websites as the helix user would need to be a member of the repository, effectively making it world readable.

feat(vcl): allow passing the x-github-token header in request

---

layouts/fastly/helix.vcl
src/fastly/dictionaries.js
test/dictionaries.test.js

Purge stop through edge dictionary

---

layouts/fastly/helix.vcl

fix(vcl): set vary headers on synthetic (error) responses

---

src/fastly/epsagon.js
src/publish.js
test/fixtures/recordings/Integration-Test_519117731/Test-publish-function-locally_1268185746/recording.har
test/integration.js

fix(vcl): disable Epsagon VCL tracing

---

layouts/fastly/helix.vcl

fix(vcl): reduce workspace usage

---

layouts/fastly/helix.vcl

Alternative to #869 as suggested by @tripodsan – @rofe please test. Fixes #830

fix(content): allow cors headers for lnk request type

---

layouts/fastly/helix.vcl

uses https://github.com/adobe/helix-rum-collector on https://rum.hlx3.page to support RUM collection as implemented in https://github.com/adobe/theblog/pull/682

feat(vcl): add support for rum collection

---

src/rgx/block.js
test/fixtures/allowed-paths.txt

see https://github.com/adobe/theblog/pull/682#issuecomment-849460506

fix(block): allow .rum path

---

layouts/fastly/helix.vcl

fix(rum): pass rum requests and do not forward cookies
