adobe/helix-publish

layouts/fastly/helix.vcl

This started out as a refactor to fix the handling of redirects from runtime for static files that are larger than the limit. It then quickly evolved to reworking how restarts are done, which is documented in the large comment at the top.
Other things were fixed along the way, mostly related, so not split out into separate changes:
* Deduplicating code in `vcl_miss` and `vcl_pass`
* Deduplicating `X-URL` and `X-Orig-URL`
* Rename `X-Static` to `X-Request-Type`
* Improve handling of proxy strains
* Use less resources (headers/variables)
* Be consistent about where to set the backend
* Split `Image` out into a separate request type
* Leak less data in headers to origins

Massive refactor of helix.vcl

---

package-lock.json
package.json
src/fastly/dictionaries.js
test/dictionaries.test.js

This is using the new https://github.com/adobe/fastly-native-promises/tree/v1.6.0#fastlybulkupdatedictitemsversion-name-items--promise API introduced in fastly-native-promises@1.6.0 to fix #6 
Unfortunately, I'm experiencing constant intermittent errors:
- constant: it's never running though successfully
- intermittent: at least one (in most cases 3-4) of the 11 `PATCH` requests we are making to update the dictionaries is failing to establish a connection to the server
```
-      "RequestError: Error: ESOCKETTIMEDOUT"
-      "    at new RequestError (/code/helix-publish/node_modules/request-promise-core/lib/errors.js:14:15)"
-      "    at Request.plumbing.callback (/code/helix-publish/node_modules/request-promise-core/lib/plumbing.js:87:29)"
-      "    at Request.RP$callback [as …
```

Use the new bulk update API for dictionary updates

---

.circleci/config.yml
index.js
package.json
test/integration.js

Implements a custom status check for Pingdom and fixes #15 
To make deployments more robust, I'm deploying to a test action first and check if https://adobeioruntime.net/api/v1/web/helix/default/publish-test gives a status code of 200 for GET requests. That URL can also be used to preview the status check.

Pingdom Status Check

---

README.md
layouts/fastly/helix.vcl
package.json
src/fastly/redirects,js
src/fastly/redirects.js
src/fastly/vcl-utils.js
src/publish.js
test/fixtures/full.yaml
test/integration.js
test/redirects.test.js
test/vcl-utils.test.js

This is a cumulative PR for
- #30 (redirects)
- #32 (images)
- #33 (`X-From-Edge`)
and amends/obsoletes
- #7 (VCL refactor)
- #27 (redirect drafts)
The tests now ensure that Fastly accepts the VCL we upload, which is a great help. 😉

Refactor fixes & Redirect Management

---

layouts/fastly/helix.vcl

provide two new resource types for static resources: .esi to replace a static URL with a cacheable static URL and .hlx_[0-9a-f]+ for resources that are cached forever in the browser
In order to increase the cache efficiency of static resources, we are implementing a multi-stage process which replaces the generic, short and uncacheable URLs of static resources like `/scripts/site.js` with long and version-specific URLs like `/scripts/site.js.hlx_f7c3bc1d808e04732adf679965ccc34ca7ae3441`. This is done by offering a virtual resource like `/scripts/site.js.esi` that can be included in an ESI tag like `<script src="<esi:include src="/scripts/site.js.esi" />">` from within HTML, JS or CSS (the replacement of `.js` and `.css` file endings iwth `.js.esi` and `.css.esi` will be handled in …

Enable Better Caching for Static Resources

---

package-lock.json
package.json
src/fastly/backends.js
src/fastly/vcl-utils.js
test/backends.test.js
test/fixtures/demo-reset.vcl
test/fixtures/demo.yaml
test/fixtures/full-reset.vcl
test/fixtures/full-resolve.vcl
test/fixtures/full.yaml
test/fixtures/urls-resolve.vcl
test/vcl-utils.test.js

Fixes #64 by rewriting `https://helixdomain.com/newpath` to `https://backenddomain.com/oldpath` using the `strain[].origin.path` property and the `strain.url.path` property.
Note: this is a breaking change that changes the behavior of all proxy strains. If you had a proxy strain for `https://helixdomain.com/foobar/` then requests to `https://helixdomain.com/foobar/index.html` would go go `https://backenddomain.com/foobar/index.html`, now they go to `https://backenddomain.com/index.html`. To restore the old behavior, add a `path` to each `origin` in a proxy strain.

Proxy Strain Subdirectory Support

---

layouts/fastly/helix.vcl
src/publish.js

with https://github.com/adobe/helix-dispatch/releases/tag/v2.0.0 the URL of the dispatch action has dropped the experimental. This change uses the new version, while also pinning the version to `v2` as discussed here: https://github.com/adobe/helix-publish/issues/128#issuecomment-513220213
fixes #128 – partial revert of #129

feat(dispatch): use released dispatch version instead of latest

---

layouts/fastly/helix.vcl

I noticed that some published sites leak the following debug headers:
```
X-PreFetch-Miss
X-PreFetch-Pass
X-PostFetch
```
These temporary headers are used to transport trace information to shield nodes and back and to finally reconstruct the full vcl trace information in `vcl_deliver`. 
This PR makes sure they are unconditionally removed in `vcl_deliver`.

feat(helix.vcl): avoid leaking of debug headers

---

README.md
src/publish.js

BREAKING CHANGE: This changes the default dispatch version from v2 to v3. v3 introduces dynamic defaults (fallback to `default.htnl` in the same folder if file can't be found), which is a breaking change
enables dynamic defaults, see https://github.com/adobe/helix-dispatch/issues/138
**Note:** as this is a breaking change, it will require a new helix-cli version, too.

feat(dispatch): update to dispatch@v3 with dynamic defaults

---

layouts/fastly/helix.vcl

We have been sending requests to raw.githubusercontent.com with `Authorization: token (null)` in the headers. GitHub responds to these requests with a status 404, as the token is invalid
fixes #274 and https://github.com/adobe/helix-pages/issues/79

Fix Large Image Support

---

layouts/fastly/helix.vcl
package-lock.json
src/fastly/algolia.js
src/fastly/backends.js
src/fastly/vcl.js
src/index.js
src/publish.js
test/algolia.test.js
test/fixtures/example-queries.vcl
test/fixtures/example-queries.yaml
test/fixtures/recordings/Integration-Test_519117731/Test-publish-function-locally_1268185746/recording.har
test/integration.js
test/vcl.test.js

This PR allows us to hide Algolia queries behind the `/_query/{index}/{name}` URL and cache requests to Algolia. 
You can try by going to https://www.primordialsoup.life/_query/blog-posts/all?page=1 (this is using a clone of theblog's index)
See https://github.com/davidnuescheler/theblog/issues/44 and https://github.com/adobe/helix-index-files/issues/3
In order to be useful, we need to adjust `helix-cli` to read the Query config and send it as part of the publish request. I'll start on this as soon as this PR has been merged.

Algolia proxy

---

package.json

Right now, running `hlx publish` fails due to the missing schemas.

fix(package): include required schemas in deployment

---

src/fastly/backends.js
test/backends.test.js

when no algolia app id is provided, the algolia backend will be created anyway, but using `undefined-dsn.algolia.net` as the hostname
fixes #298

fix(query): guard against missing algolia app id parameter

---

layouts/fastly/helix.vcl

this is a speculative fix for https://github.com/davidnuescheler/theblog/issues/92 – the behavior @drwilco and I are seeing is this: when requesting a font with the x-forwarded-host header, it will return a 404 – unless the same font has been requested without the header and still resides in the Adobe Fonts CDN cache. This fix always removes the header, so that no cache poisoning is possible
fix https://github.com/davidnuescheler/theblog/issues/92

fix(vcl): remove x-forwarded-host header when talking to Adobe Fonts

---

layouts/fastly/helix.vcl

Basic idea: when the statically configured queries (see https://github.com/adobe/helix-publish/blob/master/test/fixtures/example-queries.vcl for an example document) do not match, fall back to calling https://github.com/adobe/helix-query-index (e.g. https://adobeioruntime.net/api/v1/web/helix/helix-services/query-index@v1/blog-posts/all?__hlx_owner=trieloff&__hlx_repo=helixdemo&__hlx_ref=3aea5fd4cd4d40f5f7c6ce3d74c6f20999903cd3) which will 307 redirect to a proper Algolia search URL. When our VCL sees that URL, it should just fetch and deliver *that*.

Fallback queries

---

layouts/fastly/helix.vcl

Using hash_always_miss is a flawed approach because it can cause
a thundering herd to the new backend. (Not to be confused with the
thundering herd to the original backend.) When the hash_always_miss
VCL was written, there was no good alternative though. Now that
Fastly handles Vary superseding correctly, that is a much better
alternative. See also my talk about this at https://vimeo.com/376921144
And to avoid confusion Redirect is now renamed to Static/Redirect, and
hlx_type_redirect to hlx_type_static_redirect.

Use Vary instead of hash_always_miss and change Redirect to Static/Redirect

---

package-lock.json
package.json
src/fastly/vcl-utils.js
test/fixtures/full-resolve.vcl
test/fixtures/full.yaml
test/fixtures/urls-resolve.vcl
test/fixtures/urls.yaml

adobe/helix-publish#332 has been merged by squashing, which means no release has been triggered. The release itself should have been a major release, as support for text-based conditions has been dropped (breaking changes).
This PR reverts the squashed merge, so that I can create a proper merge.
/cc @dominique-pfister

Revert "Conditions support in helix-publish"

---

layouts/fastly/403.html
layouts/fastly/500.html
layouts/fastly/502.html
layouts/fastly/503.html
layouts/fastly/504.html
layouts/fastly/951.html
layouts/fastly/952.html
layouts/fastly/953.html
layouts/fastly/generic-error.html
package.json

Updated the error page design from cloudy errors to a glitchy error page with a more subtle animation.
The new error pages for 403, 502, 503, and 504 aren't used in VCL yet.

feat(errors): new error pages for errors 403, 404, 500, 502, 503, 504

---

layouts/fastly/helix.vcl

WIP PR for #378 
I have created a deployment with all error cases: 
- [https://alex.helix-demo.xyz/e.403.html](https://alex.helix-demo.xyz/e.403.html)
- [https://alex.helix-demo.xyz/e.404.html](https://alex.helix-demo.xyz/e.404.html)
- [https://alex.helix-demo.xyz/e.500.html](https://alex.helix-demo.xyz/e.500.html)
- [https://alex.helix-demo.xyz/e.502.html](https://alex.helix-demo.xyz/e.502.html)
- [https://alex.helix-demo.xyz/e.503.html](https://alex.helix-demo.xyz/e.503.html)
- [https://alex.helix-demo.xyz/e.504.html](https://alex.helix-demo.xyz/e.504.html)
Error code project source is here: https://github.com/kptdobe/helix-errors
I also merged https://github.com/adobe/helix-publish/pull/379 in this PR to have the full picture.
But I am bit stuck: non of those uses the custom error …

feat(error): Propagate specific errors

---

package-lock.json
package.json
src/fastly/dictionaries.js
src/publish.js
test/index.test.js

I've experienced timeout errors when updating dictionaries due to node's limited DNS pool. This PR reports timeouts as 504 and prevents them.
before:  https://dashboard.epsagon.com/spans/0e7959ea-a1ea-54d6-f27d-4c3ecd6b2857?tab=timeline
after: https://dashboard.epsagon.com/spans/0e795a70-0b38-eeca-de75-9359f9de0283?tab=timeline

fix(http): report timeouts and reduce parallelism

---

layouts/fastly/helix.vcl

BREAKING CHANGE: content proxy v2 uses new data embed and gdocs services.
- requests to json now returns an object instead of and array [0]
- gdocs2md now has a different table handling [1]
- gdocs2md supports author friendly names [2]
[0] https://github.com/adobe/helix-data-embed/commit/9d1e924acc3aa6488b464a3cdc4a3bf68e3843bc
[1] https://github.com/adobe/helix-gdocs2md/commit/e4befdbaed4a5319b2cca4be8507f153bedcc68a
[2] https://github.com/adobe/helix-gdocs2md/commit/3aca7b387bbee977f84e61ce823ff6271b1b0a8d

feat(deps): use content-proxy v2

---

.circleci/config.yml
package.json
src/publish.js
test/block.test.js
test/integration.js
test/tracer.test.js

otherwise the fastly api fails
fixes #628

fix(publish): reduce parallelism in updating vcl

---

layouts/fastly/helix.vcl

fix: allow table and sheet as parameters

---

package.json
src/check-pkgs.js
src/fastly/backends.js

because fastly suddenly requires it? or something changed with the cert?

fix(backends): always set sni hostname for runtime

---

layouts/fastly/helix.vcl

fix(preflight): version lock is lost after preflight

---

src/rgx/block.js
test/fixtures/blocked-paths.txt

any URL code sequence of a % that is not followed by two hex digits will be rejeceted by Adobe I/O Runtime Gateway with a 500. This change rejects it already at the CDN level.

fix(block): block invalid URL-code sequences

---

src/fastly/vcl-utils.js

for configs that used preflight conditions (like helix-pages), the request type would be reset every time, breaking a crucial smoke test. This change restores the previous behavior
see https://github.com/adobe/helix-pages/issues/671

fix(vcl): allow setting request type from outside

---

src/fastly/vcl-utils.js

The `embed` request type is quite different from other request types, as it goes to a different host, so the typical method of determining owner, repo, ref does not work. On the other hand, the underlying service does not make use of strains at all, so there is litte point in trying to resolve a strain. This change will skip preflight requests for embeds. A side effect is that the version-picker for helix-embed won't work for users in helix-pages.
fixes #725

fix(preflight): do not process preflight requests for external embeds

---

src/check-pkgs.js

adds the version lock header to the outgoing request
fixes #740

fix(check-packages): pass version-lock header when verifying package

---

layouts/fastly/helix.vcl

other than the explicit selection via the x-strain header, this one does not affect the cachability. This also means that changes to x-stealty-strain will only become effective once the cache has expired
see https://github.com/adobe/helix-pages/pull/695#issuecomment-781187574

feat(strains): allow strain selection via x-stealthy-strain header

---

layouts/fastly/helix.vcl

sitemaps should be served as content binaries
BREAKING CHANGE: fixes #783 depends on adobe/helix-content-proxy#315 – breaks sitemap serving for sites that serve `/` from Google or Word and have their sitemap only on GitHub. You either need to copy the `sitemap.xml` to your content repository (recommended) or create a `helix-fstab.yaml` entry for the sitemap to continue serving it from GitHub (this time via content proxy instead of static)

feat(sitemap): serve sitemap.xml from content proxy

---

layouts/fastly/helix.vcl

Only `vary` on `XFH` for `.html` and `/robots.txt`
resolves #782

feat: Do not vary on XFH for non-html

---

layouts/fastly/helix.vcl

The current implementation is based on the `.html` extension. That doesn't work for html requests without extension. This PR uses  the response `content-type` to determine if it's an html requests.

fix(helix.vcl): vary on XFH only for html responses or /robots.txt

---

layouts/fastly/helix.vcl

a 401 from the backend was unhandled so far (500), now we propagate it as a 403 (Forbidden) instead of 401 (Unauthorized) as a 401 would ask the browser for credentials (HTTP Basic Auth) that we do not want to handle anyway.
fixes #893

fix(vcl): fix 401 to 500 propagation, propagate as 403 instead

---

layouts/fastly/helix.vcl

two key issues fixed: 1. the `Embed` request type wasn't detected when the hostname pointed to universal runtime 2. the X-Backend-URL wasn't set, so that the wrong function (HTML pipeline) would be invoked and fail
fixes adobe/helix-pages#971

fix(embeds): fix broken server-side embeds
